### ISSUE TITLE
exec action doesn't return the original exit code

### ISSUE THREAD

**Issue by goneri** [ansible/ansible-navigator#1215] opened 2022-04-28 20:14 UTC
##### ISSUE TYPE

- Bug Report

##### SUMMARY

The `exec` action return 0 even in case of failure.

```
$ ansible-navigator exec --eei my-ee --mode=stdout --pull-policy=never -- bash -c 'exit 1'
$ echo $?
```

##### ANSIBLE-NAVIGATOR VERSION

```
$ ansible-navigator --version
ansible-navigator 2.0.1.dev3+g2d24704
```

**Comment by shatakshiiii** [comment] 2022-10-31 06:04
Could you please check if the issue persists with the latest release of ansible-navigator or not. If the issue is being resolved you can go ahead and close it.

**Comment by Akasurde** [comment] 2022-10-31 06:14
@goneri ^^

**Comment by goneri** [comment] 2022-10-31 14:04
Hi @shatakshiiii and @Akasurde, I'm afraid it's still broken.

```
$ ansible-navigator --version
ansible-navigator 2.2.0
$ ansible-navigator exec --eei quay.io/ansible/awx-ee:latest --mode=stdout --pull-policy=never -- bash -c 'exit 1' && echo problem still exists
problem still exists
```

**Comment by shatakshiiii** [comment] 2022-10-31 14:37
Thanks @goneri for investigating it again. We'll look forward to fix that.

**Closed** 2022-11-09 02:49 UTC
Labels: bug, AAP
