### ISSUE TITLE
Clean setup.py

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible-navigator#684] opened 2021-12-09 18:24 UTC
As part of PEP-517 agenda we should clean the setup.py file and only make use of `setuptools-scm`, reducing its size to 2-3 lines.

Ideally we would have removed the file completely but we will postpone this until we have confirmation that rpm building tools are updated to be able to build python projects that do not have a `setup.py` file.

**Comment by cidrblock** [comment] 2021-12-09 18:24
TY for this

**Comment by webknjaz** [comment] 2021-12-10 16:35
Duplicate of https://github.com/ansible/ansible-navigator/issues/553 and https://github.com/ansible/ansible-navigator/issues/554.

**Closed by webknjaz** 2021-12-10 16:35 UTC
Labels: bug, new
