### ISSUE TITLE
[:run] execution abruptly ends when running a playbook that takes longer time to finish

### ISSUE THREAD

**Issue by NilashishC** [ansible/ansible-navigator#361] opened 2021-05-27 09:17 UTC
### Summary

While running a integration test suite with `ansible-navigator`, the execution abruptly ends after some time with the following traceback (with both --ce podman and docker):

```
2021-05-26T09:39:02.000536576Z: open pidfd: No such process
ERRO[0299] Error forwarding signal 15 to container 90b9cfddf63490126585647640ae2ac1ff93ff8d89bcbf46cd470cbffc0e82d1: error sending signal to container 90b9cfddf63490126585647640ae2ac1ff93ff8d89bcbf46cd470cbffc0e82d1: `/usr/bin/crun kill 90b9cfddf63490126585647640ae2ac1ff93ff8d89bcbf46cd470cbffc0e82d1 15` failed: exit status 1
```
### Steps to reproduce

Happens with multiple network integration test suites. But here's a setup with OVS.

-  `git clone --branch ee_test https://github.com/NilashishC/openvswitch.openvswitch`
- `ansible-navigator run --eei quay.io/ansible/network-ee:stable-2.11 $PWD/openvswitch.openvswitch/tests/integration/site.yaml -i $PWD/inventory --mode=stdout --ce podman --ll debug`

Runner artifact "status" says "timeout".

**Comment by ganeshrn** [comment] 2021-05-31 04:30
@NilashishC Please try with the latest navigator code. Most likely the issue is already fixed by PR https://github.com/ansible/ansible-navigator/pull/340

**Comment by cidrblock** [comment] 2021-06-03 14:55
fixed in runner a5, which will be used in navigator B1.  The subprocess timeout is set to None by default

**Closed by cidrblock** 2021-06-03 14:55 UTC
Labels: research
