### ISSUE TITLE
Add navigator settings information to artifact file

### ISSUE THREAD

**Issue by ganeshrn** [ansible/ansible-navigator#615] opened 2021-11-18 04:11 UTC
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

The active setting for navigator is not added a part of artifact file which will be required to debug issues while sharing artifact files

**Comment by cidrblock** [comment] 2021-11-29 13:58
related #603

**Comment by cidrblock** [comment] 2021-11-29 14:00
duplicate #603

**Comment by webknjaz** [comment] 2021-11-29 14:00
Duplicate of #603

**Closed by webknjaz** 2021-11-29 14:00 UTC
Labels: enhancement, AAP
